import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { FileText, Home, Map as MapIcon, MessageSquare, Settings } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-zinc-50">
          <header className="h-16 border-b bg-white">
            <div className="mx-auto flex h-full w-full max-w-6xl items-center justify-between px-6">
              <Link href="/" className="text-sm font-semibold tracking-tight text-zinc-900">
                MissionMind
              </Link>
              <nav className="flex items-center gap-4 text-sm text-zinc-700">
                <Link href="/" className="flex items-center gap-2 hover:text-zinc-900">
                  <Home className="h-4 w-4" />
                  Dashboard
                </Link>
                <Link href="/chat" className="flex items-center gap-2 hover:text-zinc-900">
                  <MessageSquare className="h-4 w-4" />
                  Chat
                </Link>
                <Link href="/map" className="flex items-center gap-2 hover:text-zinc-900">
                  <MapIcon className="h-4 w-4" />
                  Map
                </Link>
                <Link href="/reports" className="flex items-center gap-2 hover:text-zinc-900">
                  <FileText className="h-4 w-4" />
                  Reports
                </Link>
                <Link href="/settings" className="flex items-center gap-2 hover:text-zinc-900">
                  <Settings className="h-4 w-4" />
                  Settings
                </Link>
              </nav>
            </div>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
